python train.py --data_dir ./dataset/docred \
--transformer_type bert \
--model_name_or_path bert-base-cased \
--train_file train_annotated.json \
--dev_file dev_revised.json \
--test_file dev_revised.json \
--train_batch_size 6 \
--test_batch_size 8 \
--gradient_accumulation_steps 1 \
--num_labels 4 \
--learning_rate 5e-5 \
--max_grad_norm 1.0 \
--warmup_ratio 0.06 \
--num_train_epochs 30 \
--seed 66 \
--num_class 97 \
--loss_type HingeABL \
--save_name docred_bert_HingeABL \
--proj_name docred \
--run_name bert_HingeABL
